version: "3.8"

services:
  mongo:
    container_name: mongo
#    env_file: ../.env/mongodb.env
    image: mongo:3.6
    volumes:
      - ./data/mongo:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo_express
    depends_on:
      - 'mongo'
    ports:
      - '8081:8081'
    restart: always
