
version: '3.1'

secrets:
  mongo-root-passwd:
    file: mongo-root-passwd
  mongo-user-passwd:
    file: mongo-user-passwd

services:
  mongo:
    image: mongo:3.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-passwd
      MONGO_INITDB_USERNAME: $MONGO_USER
      MONGO_INITDB_PASSWORD_FILE: /run/secrets/mongo-user-passwd
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    secrets:
      - mongo-root-passwd
      - mongo-user-passwd




#version: "3.8"
#
#services:
#
### The actual Mongo DB
#  db:
#    env_file: ../.env/mongodb.env
#    image: 'mongo'
#    container_name: nyjs_mongodb
#    ports:
#      - '27017:27017'
#
### GUI Tool alternative to Adminer
##  mongo-express:
##    image: mongo-express:0.54.0
##    container_name: mongo_express
##    depends_on:
##      - db
##    ports:
##      - 8081:8081
##    restart: always
#
#  mongo-express:
#    image: mongo-express:0.54.0
#    container_name: mongo_express
#    depends_on:
#      - 'db'
#    ports:
#      - '8081:8081'
#    restart: always
#
#
### Adminer Graphical Database System
##  adminer:
##    container_name: nyjs_adminer_x
##    image: adminer
##    restart: always
##    ports:
##      - 8080:8080
#
#
